image: maven:3.6-jdk-8-slim

stages:
  - package
  - pages


package :
  stage : package
  script: mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/batchPhoto-0.0.1-SNAPSHOT.jar
pages:
  stage: pages
  script:  
    - mvn package -Dmaven.test.skip=true  
  artifacts:    
    paths:    
      - target/batchPhoto-0.0.1-SNAPSHOT.jar  
  only:  
      - master
